image: php:latest
pipelines:
  default:
    - step:
        runs-on:
          - self.hosted
          - linux
        name: run pytest
        script: 
          - "apt-get update && apt-get install -y git unzip"
          - "git submodule sync"
          - "git submodule update --init --recursive"
          - "cd baserepo"
          - "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
          - "composer install --prefer-dist --no-interaction --no-progress"
          - "composer require phpunit/phpunit"
          - "cp .env.example .env"
          - "php artisan key:generate"
          - "vendor/bin/phpunit"
