version: '2.1'
jobs:
  php-unit-tests:
    docker:
      - image: cimg/php:8.3
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          command: |
            cd baserepo
            apt-get update && apt-get install -y unzip
            curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            composer install --prefer-dist --no-interaction --no-progress
            composer require phpunit/phpunit
            cp .env.example .env
            php artisan key:generate
            vendor/bin/phpunit
workflows:
  php-unit-tests-workflow:
    jobs:
      - php-unit-tests
