steps:
  - command: |
    cd baserepo
    apt-get update && apt-get install -y unzip
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
    composer install --prefer-dist --no-interaction --no-progress
    composer require phpunit/phpunit
    cp .env.example .env
    php artisan key:generate
    vendor/bin/phpunit
