steps:
  - command: |
      cd baserepo
      php composer.phar install --prefer-dist --no-interaction --no-progress
      cp .env.example .env
      php artisan key:generate
      vendor/bin/phpunit
