name: PHP unit tests
on:
  push:
  pull_request:

jobs:

  tests:
    name: Unit Tests
      
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Run tests 
        run: |
          cd baserepo
          composer install --prefer-dist --no-interaction --no-progress
          cp .env.example .env
          php artisan key:generate
          vendor/bin/phpunit
