name: PHP unit tests
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:

  tests:
    name: Unit Tests

    strategy:
      fail-fast: true 
      
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          submodules: recursive

      - name: Extract baserepo
        run: "rm -rf baserepo/.git && mv .git/modules/baserepo baserepo/.git && mv baserepo ~/ && cd .. && rm -rf php-unit-tests && mv ~/baserepo php-unit-tests && cd php-unit-tests/ && sed -i '/worktree/d' .git/config"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Run tests 
        run: |
          composer install --prefer-dist --no-interaction --no-progress
          cp .env.example .env
          php artisan key:generate
          vendor/bin/phpunit
