name: PHP unit tests
on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:

  tests:
    name: Unit Tests

    env:
      extensions: amqp,apcu,igbinary,intl,mbstring,memcached,redis,relay

    strategy:
      matrix:
        include:
          - php: '8.3'
      fail-fast: false
      
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          submodules: recursive

      - name: Extract baserepo
        run: "rm -rf baserepo/.git && mv .git/modules/baserepo baserepo/.git && mv baserepo ~/ && cd .. && rm -rf php-unit-tests && mv ~/baserepo php-unit-tests && cd php-unit-tests/ && sed -i '/worktree/d' .git/config"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          ini-values: date.timezone=UTC,memory_limit=-1,default_socket_timeout=10,session.gc_probability=0,apc.enable_cli=1,zend.assertions=1
          php-version: "${{ matrix.php }}"
          extensions: "${{ env.extensions }}"
          tools: flex
        
      - name: Configure environment
        run: |
          # composer setup
          (php --ri relay 2>&1 > /dev/null) || sudo rm /etc/php/*/cli/conf.d/20-relay.ini
          COMPOSER_HOME="$(composer config home)"
          ([ -d "$COMPOSER_HOME" ] || mkdir "$COMPOSER_HOME") && cp .github/composer-config.json "$COMPOSER_HOME/config.json"
          echo COMPOSER_UP='composer update --no-progress --ansi' >> $GITHUB_ENV

          SYMFONY_VERSION=$(grep ' VERSION = ' src/Symfony/Component/HttpKernel/Kernel.php | cut -d "'" -f2 | cut -d '.' -f 1-2)
          php .github/build-packages.php HEAD^ $SYMFONY_VERSION src/Symfony/Bridge/PhpUnit
          echo SYMFONY_VERSION=$SYMFONY_VERSION >> $GITHUB_ENV
          echo COMPOSER_ROOT_VERSION=$SYMFONY_VERSION.x-dev >> $GITHUB_ENV
          echo SYMFONY_REQUIRE=">=${SYMFONY_VERSION}" >> $GITHUB_ENV
          echo COLUMNS=150 >> $GITHUB_ENV

          # test commands setup
          echo COMPONENTS=$(find src/Symfony -mindepth 2 -type f -name phpunit.xml.dist | xargs -I{} dirname {}) >> $GITHUB_ENV
          echo PHPUNIT="$(pwd)/phpunit --exclude-group benchmark,intl-data,integration" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          echo "::group::composer update"
          $COMPOSER_UP
          echo "::endgroup::"
          echo "::group::install phpunit"
          ./phpunit install
          echo "::endgroup::"
      - name: Run tests
        run: |
          _run_tests() {
            local ok=0
            local title="$1$FLIP"
            OUTPUT=$(bash -xc "$2" 2>&1) || ok=$?
            if [[ $ok -ne 0 ]]; then
              printf "%-80s\e[31m%10s\e[0m\n" $title 'FAIL'
            else
              printf "%-80s\e[32m%10s\e[0m\n" $title 'OK'
            fi
            echo -e "\n${OUTPUT}\\n"
          }
          export -f _run_tests
          echo "$COMPONENTS" | xargs -n1 | parallel -j +3 "_run_tests {} '$PHPUNIT {}'"
      - name: Run TTY tests
        run: |
            script -c './phpunit --group tty' 